server:
  port: 8081

spring:
  redis:
    host: 42.203.52.207
    port: 51482
    password: admin123
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: -1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.203.52.207:64428/bluebook?useSSL=false&serverTimezone=UTC
    username: root
    password: admin123
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  profiles:
#    active: home

mybatis:
  type-aliases-package: com.lixy.bluebook.Entity , com.lixy.bluebook.DTO
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

logging:
  group:
    server: com.lixy.bluebook.Controller, com.lixy.bluebook.Service
    sql: com.lixy.bluebook.Dao
  level:
    root: info
    sql: debug
