spring:
  redis:
    host: 192.168.140.100
    port: 6379
    password: admin123
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: -1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.140.100:3306/bluebook?useSSL=false&serverTimezone=UTC
    username: root
    password: admin123
  rabbitmq:
    host: 192.168.140.100 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: root # 用户名
    password: 123456 # 密码